import { AppTheme } from "utils/theming.slint";
import { AppButton } from "components/AppButton.slint";
import { Divider } from "components/Divider.slint";
import { Button, ListView, ScrollView, VerticalBox, ScrollView, HorizontalBox, ProgressIndicator } from "std-widgets.slint";

export struct TokenDrop {
    mint: string,
    solscan: string,
    dexscreener: string,
    birdeye: string,
    raydium: string,
    jupiter: string,
    name: string,
    symbol: string,
    uri: string,
    is_pumpfun: bool
}

export component App inherits Window {
    preferred-width: 1200px;
    preferred-height: 800px;
    min-width: 940px;
    min-height: 470px;
    max-height: 1400px;
    background: AppTheme.background;
    no-frame: false;
    always-on-top: false;
    title: "Foxana";
    icon: @image-url("assets/defi-fox-logo-v1.png");

    in property <int> counter: 1;

    callback open_link;

    in-out property <string> url_link;


    in-out property <[TokenDrop]> token_drops;
    in-out property <[TokenDrop]> drops: [
        {
            mint: "mint1",
            solscan: "string",
            dexscreener: "string",
            birdeye: "string",
            raydium: "https://raydium.io/swap/?inputMint=sol&outputMint=DQPq9oRZm5tRRQKU7nGNd5kngDgr1RdaWVeFjafypump",
            jupiter: "string",
            name: "Wrapped Sol",
            symbol: "WSOL",
            uri: "string",
            is_pumpfun: true
        },
        {
            mint: "min2t",
            solscan: "string",
            dexscreener: "string",
            birdeye: "string",
            raydium: "https://raydium.io/swap/?inputMint=sol&outputMint=DQPq9oRZm5tRRQKU7nGNd5kngDgr1RdaWVeFjafypump",
            jupiter: "string",
            name: "Wrapped Sol",
            symbol: "WSOL",
            uri: "string",
            is_pumpfun: false
        },
        {
            mint: "mint3",
            solscan: "string",
            dexscreener: "string",
            birdeye: "string",
            raydium: "https://raydium.io/swap/?inputMint=sol&outputMint=DQPq9oRZm5tRRQKU7nGNd5kngDgr1RdaWVeFjafypump",
            jupiter: "string",
            name: "Wrapped Sol",
            symbol: "WSOL",
            uri: "string",
            is_pumpfun: false
        },
    ];



    ScrollView  {
        VerticalBox {
            spacing: 18px;
            padding-left: 48px;
            padding-right: 48px;
            padding-top: 21px;
            padding-bottom: 21px;

            HorizontalLayout {
                spacing: 8px;
                Rectangle {
                    border-radius: 9px;
                    width: 38px;
                    height: 38px;
                    clip: true;
                    Image {
                        source: @image-url("assets/solana-logo-mark.png");
                        image-fit: cover;
                        width: 38px;
                    }
                }
                Rectangle {
                    height: 38px;
                    max-width: 200px;
                    HorizontalLayout {
                        Text {
                            text: "SOLANA Live";
                            font-weight: 800;
                            font-size: 27px;
                        }
                        Rectangle {
                            background: @radial-gradient(circle, rgba(0,120,215,1) 0%, rgba(0,120,215,0) 100%);
                            width: 20px * abs(sin(360deg * animation-tick() / 6s));
                            height: 20px * abs(sin(360deg * animation-tick() / 6s));
                            y: 10px;
                        }
                    }
                }
            }

            for token[index] in token_drops: Rectangle {
               height: 390px;
               width: 600px;
               background: AppTheme.surface;
               border-radius: 9px;
               clip: true;
               Rectangle {
                    visible: token.is_pumpfun;
                    background: @radial-gradient(circle, #107C1045 30%, #107B1000 100%);
                    width: 900px;
                    height: 900px;
               }

               HorizontalLayout {
                   spacing: 8px;
                   width: 560px;
                   height: 370px;

                   VerticalLayout {
                       HorizontalBox {
                            Text {
                               font-size: 20px;
                               font-weight: 800;
                               vertical-alignment: top;
                               horizontal-alignment: left;
                               text:  "\{token.name} (\{token.symbol})";
                               height: 40px;
                           }
                            Rectangle {
                                visible: token.is_pumpfun;
                                border-radius: 9px;
                                width: 30px;
                                height: 30px;
                                clip: true;
                                Image {
                                    vertical-alignment: center;
                                    source: @image-url("assets/program_entites/pumpfun-logo.png");
                                    image-fit: cover;
                                    width: 30px;
                                }
                            }
                       }

                       VerticalBox {
                           HorizontalLayout {
                               height: 100px;
                               VerticalLayout {
                                    width: 540px;
                                    Text {
                                       text: "Swap Token";
                                       font-weight: 800;
                                       font-size: 16px;
                                       height: 30px;
                                  }
                                  Divider { height: 2px; }
                                  HorizontalLayout {
                                    height: 60px;
                                    spacing: 8px;
                                    padding-top: 8px;
                                    Rectangle {
                                          border-radius: 9px;
                                          background: #121212;
                                          width: 40px;
                                          height: 40px;
                                          clip: true;
                                          padding-top: 4px;
                                          Image {
                                              vertical-alignment: center;
                                              source: @image-url("assets/raydium-logo.jpg");
                                              image-fit: cover;
                                              width: 40px;
                                          }

                                          states [
                                              pressed when raydium_btn.pressed: {
                                                   opacity: 0.5;
                                              }
                                              hover when raydium_btn.has-hover: {
                                                  opacity: 0.8;
                                              }
                                          ]

                                          raydium_btn := TouchArea {
                                            mouse-cursor: pointer;
                                            clicked => {
                                                root.url_link = token.raydium;
                                                root.open_link();
                                            }
                                          }
                                      }

                                      Rectangle {
                                            border-radius: 9px;
                                            background: #121212;
                                            width: 40px;
                                            height: 40px;
                                            clip: true;
                                            padding-top: 4px;
                                            Image {
                                                vertical-alignment: center;
                                                source: @image-url("assets/jupiter-logo.png");
                                                image-fit: cover;
                                                width: 40px;
                                            }

                                            states [
                                              pressed when jupiter_btn.pressed: {
                                                   opacity: 0.5;
                                              }
                                              hover when jupiter_btn.has-hover: {
                                                  opacity: 0.8;
                                              }
                                            ]

                                            jupiter_btn := TouchArea {
                                                mouse-cursor: pointer;
                                                clicked => {
                                                    root.url_link = token.jupiter;
                                                    root.open_link();
                                                }
                                            }
                                        }
                                  }
                               }
                           }

                           HorizontalLayout {
                              height: 100px;
                              VerticalLayout {
                                   width: 540px;
                                   Text {
                                      text: "View Chart";
                                      font-weight: 800;
                                      font-size: 16px;
                                      height: 30px;
                                 }
                                 Divider { height: 2px; }
                                 HorizontalLayout {
                                   height: 60px;
                                   spacing: 8px;
                                   padding-top: 8px;
                                   Rectangle {
                                         border-radius: 9px;
                                         background: #121212;
                                         width: 40px;
                                         height: 40px;
                                         clip: true;
                                         padding-top: 4px;
                                         Image {
                                             vertical-alignment: center;
                                             source: @image-url("assets/dexscreener-logo.png");
                                             image-fit: cover;
                                             width: 40px;
                                         }

                                         states [
                                           pressed when dexscreener_btn.pressed: {
                                                opacity: 0.5;
                                           }
                                           hover when dexscreener_btn.has-hover: {
                                               opacity: 0.8;
                                           }
                                         ]

                                         dexscreener_btn := TouchArea {
                                             mouse-cursor: pointer;
                                             clicked => {
                                                 root.url_link = token.dexscreener;
                                                 root.open_link();
                                             }
                                         }
                                     }

                                     Rectangle {
                                       border-radius: 9px;
                                       background: #121212;
                                       width: 40px;
                                       height: 40px;
                                       clip: true;
                                       padding-top: 4px;
                                       Image {
                                           vertical-alignment: center;
                                           source: @image-url("assets/birdeye-logo.png");
                                           image-fit: cover;
                                           width: 40px;
                                       }
                                       states [
                                          pressed when birdeye_btn.pressed: {
                                               opacity: 0.5;
                                          }
                                          hover when birdeye_btn.has-hover: {
                                              opacity: 0.8;
                                          }
                                       ]
                                       birdeye_btn := TouchArea {
                                        mouse-cursor: pointer;
                                         clicked => {
                                             root.url_link = token.birdeye;
                                             root.open_link();
                                         }
                                       }
                                    }
                                 }
                              }
                          }
                           HorizontalLayout {
                                height: 100px;
                                VerticalLayout {
                                     width: 540px;
                                     Text {
                                        text: "View Transaction";
                                        font-weight: 800;
                                        font-size: 16px;
                                        height: 30px;
                                   }
                                   Divider { height: 2px; }
                                   HorizontalLayout {
                                     height: 60px;
                                     spacing: 8px;
                                     padding-top: 8px;
                                     Rectangle {
                                           border-radius: 9px;
                                           background: #121212;
                                           width: 40px;
                                           height: 40px;
                                           clip: true;
                                           padding-top: 4px;
                                           Image {
                                               vertical-alignment: center;
                                               source: @image-url("assets/solscan-logo.png");
                                               image-fit: cover;
                                               width: 40px;
                                           }

                                           states [
                                             pressed when solscan_btn.pressed: {
                                                  opacity: 0.5;
                                             }
                                             hover when solscan_btn.has-hover: {
                                                 opacity: 0.8;
                                             }
                                           ]
                                           solscan_btn := TouchArea {
                                                mouse-cursor: pointer;
                                                clicked => {
                                                    root.url_link = token.solscan;
                                                    root.open_link();
                                                }
                                           }
                                       }
                                   }
                                }
                            }
                       }
                   }
               }
           }
        }
    }
}